// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bbwnoanjpqxtrgzuykfk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJid25vYW5qcHF4dHJnenV5a2ZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxNDk1MzUsImV4cCI6MjA3MzcyNTUzNX0.JZ-KCmw5ngTJJA0zWjr_EcV4Ul3B6v7h7jV25ry_Cjo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});